DOCKERCOMPOSE := docker compose
DOCKERCOMPOSE_API := api
DOCKERCOMPOSE_MIGRATE := migrate
DOCKERCOMPOSE_BLOCKCHAIN := blockchain
DOCKERCOMPOSE_CRAWLER := crawler
DOCKERCOMPOSE_CRONJOB := cronjob
DOCKERCOMPOSE_POSTGRES := postgres
DOCKERCOMPOSE_REDIS := redis

RUN_API := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_API)
RUN_MIGRATE := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_MIGRATE)
RUN_BLOCKCHAIN := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_BLOCKCHAIN)
RUN_CRAWLER := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_CRAWLER)
RUN_CRONJOB := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_CRONJOB)
RUN_POSTGRES := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_POSTGRES)
RUN_REDIS := $(DOCKERCOMPOSE) up -d $(DOCKERCOMPOSE_REDIS)

RUN := $(DOCKERCOMPOSE) up -d

STOP_API := $(DOCKERCOMPOSE) stop -d $(DOCKERCOMPOSE_API) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_API)
STOP_MIGRATE := $(DOCKERCOMPOSE) stop -d $(DOCKERCOMPOSE_MIGRATE) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_MIGRATE)
STOP_BLOCKCHAIN := $(DOCKERCOMPOSE) stop -d $(DOCKERCOMPOSE_BLOCKCHAIN) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_BLOCKCHAIN)
STOP_CRAWLER := $(DOCKERCOMPOSE) stop -d $(DOCKERCOMPOSE_CRAWLER) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_CRAWLER)
STOP_CRONJOB := $(DOCKERCOMPOSE) stop -d $(DOCKERCOMPOSE_CRONJOB) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_CRONJOB)
STOP_POSTGRES := $(DOCKERCOMPOSE) stop -d $(DOCKERCOMPOSE_POSTGRES) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_POSTGRES)
STOP_REDIS := $(DOCKERCOMPOSE) stop -d $(DOCKERCOMPOSE_REDIS) && $(DOCKERCOMPOSE) rm -f $(DOCKERCOMPOSE_REDIS)

